### ISSUE TITLE
Add character classes to the parser

### ISSUE THREAD

**Issue by kodo-pp** [writing-regexps-2021-22/writing-regexps#1]
## Feature Description
We need to parse [character classes](https://www.regular-expressions.info/refcharclass.html).

## Development Branch
[`feature/character-classes`](https://github.com/writing-regexps-2021-22/writing-regexps/tree/feature/character-classes)

## Tasks
- [x] Add character class data structures.
    - [x] `std::ostream` serialization
    - [x] JSON serialization
    - [x] API reference documentation
- [x] Add character class parsing rules.
- [x] Add tests for character class parsing.
    - [x] Parse correctness
    - [x] Interaction with other regex components
    - [x] Correctness of parse errors
- [x] Add the new components to the [specification](https://writing-regexps-2021-22.github.io/docs/interface-spec/readme.html).
    - [x] Character classes
    - [x] `InvalidRange` error
