### ISSUE TITLE
Start using `FMT_STRING` when we do `fmt::format` or `fmt::print`

### ISSUE THREAD

**Issue by kodo-pp** [writing-regexps-2021-22/writing-regexps#2]
## Enhancement Description
[`FMT_STRING`](https://fmt.dev/latest/api.html#c.FMT_STRING) is a macro that enables compile-time checks of string formatting, which can help catch errors (e.g. wrong argument count) as early as possible and quickly pinpoint the location of error. It is currently completely opt-in. It probably makes sense to rewrite the existing code to use this macro, but it is unclear if its usage should be enforced via the `FMT_ENFORCE_COMPILE_STRING` feature macro.

## Development Branch
TODO

## Tasks
- [ ] Adapt `regex-parser` to use `FMT_STRING`.
- [ ] Adapt `regex-server` to use `FMT_STRING`.
- [ ] Decide if `FMT_ENFORCE_COMPILE_STRING` should be set.
