### ISSUE TITLE
`regex-server` is susceptible to stack overflow

### ISSUE THREAD

**Issue by kodo-pp** [writing-regexps-2021-22/writing-regexps#3]
## Description
Due to unbounded recursion in the regex parser when parsing groups, malicious input can be crafted to crash the regex server executable.

Example: "`(`" repeated 10000 times.

### Approaches to the fix
1) Limit the recursion depth artificially.
  **Pros**: Perhaps the simplest option.
  **Cons**: The bound on the recursion depth is considerably high. Also, we will refuse to parse many valid regular expressions.
2) Choose another parsing algorithm (e.g. LR(1)).
  **Pros**: LR(1) is non-recursive by design. No artificial restrictions.
  **Cons**: A huge amount of work needs to be done again. Probably impractical at this stage. Also, may be less flexible (e.g. not allowing dialect-dependent parsing).
3) Use delayed recursive rule invocation similarly to asynchronous code.
    1) Using callbacks
    **Pros**: No artificial restrictions, comparatively little support code, tight recursion depth bound.
    **Cons**: Code will become even more clumsy.
    2) Using C++20 coroutines
    **Pros**: No artificial restrictions, tight recursion depth bound, little changes to how the parse rule code looks like.
    **Cons**: A lot of support code is needed. Also, I need to learn how the C++20 coroutine interface works.
4) Leave as is.
  **Pros**: No work needs to be done.
  **Cons**: A security hole will remain.

## Development branch
TODO

## Tasks
- [ ] Learn about C++20 coroutines.
- [ ] Choose the approach to the fix.
- [ ] TBD depending on the approach.

**Comment by kodo-pp** [comment]
Recursion depth has been limited artificially.
