### ISSUE TITLE
Add regular expression execution

### ISSUE THREAD

**Issue by kodo-pp** [writing-regexps-2021-22/writing-regexps#4]
## Feature Description
We need to run through the process of execution of regular expressions on arbitrary strings. This needs to be done both as a library and as a server-side interface.

Something that the interface should look like is presented [here](https://gist.github.com/kodo-pp/6655bb9a411f7a335fe686dcc790e9ad).

## Development Branch
[`feature/execution`](https://github.com/writing-regexps-2021-22/writing-regexps/tree/feature/execution)

## Tasks
- [x] Add a server-side stub so that minimal testing is available.
- [x] Create a skeleton for the new library and its tests.
- [x] Implement execution in the library.
- [x] Add tests for correct execution.
    - [x] Decide on the type of tests needed (Unit / Integration?).
    - [x] Implement the selected type of tests.
- [x] Implement the server-side interface for invocations of this method.
    - [x] Define this interface in the [spec](https://writing-regexps-2021-22.github.io/docs/interface-spec/readme.html).
